### PR TITLE
Sphinx: Add inventory decoder for Sphinx

### PR DESCRIPTION
**Pull request by amotl**
## About
Operational tasks about decoding Sphinx inventories.

## References
- https://github.com/crate/crate-docs/pull/104
- https://github.com/crate/crate-docs/issues/105

### CODE REVIEW

**Comment by amotl** [comment]
It looks like those tools and patches revolve around the same topics. Maybe Markdown output has not been considered yet?

- https://github.com/bskinn/sphobjinv
- https://github.com/webknjaz/intersphinx-untangled [[web]](https://webknjaz.github.io/intersphinx-untangled/)
- [Make intersphinx (a.k.a. external references) more user friendly](https://github.com/orgs/sphinx-doc/discussions/12152)
- https://github.com/sphinx-doc/sphinx/pull/12190

/cc @bskinn, @webknjaz, @chrisjsewell

**Comment by webknjaz** [comment]
@amotl I also consider https://github.com/sphinx-doc/sphinx/issues/8211 related

**Comment by webknjaz** [comment]
> Maybe Markdown output has not been considered yet?

*output*? Why?

**Comment by amotl** [comment]
Dear @webknjaz,

thanks a stack for your reply, and for suggesting the reference to your post https://github.com/sphinx-doc/sphinx/issues/8211, I've added it to the summary note above.

### Markdown FTW
>> Maybe Markdown output has not been considered yet?
>
> output? Why?

We usually reach out to Markdown generation these days, because the output can be used both as a text-only variant, and for upgrading to HTML by sending it through a corresponding Markdown renderer. In this way, text output from utility programs becomes super versatile, because it can be easily shared on all systems understanding Markdown, like GitHub and Discourse [^1], which we use most of the time.

By using Markdown, it was easy to convey different sections of output into a single output file. In this case, the inventory decoder needed to take into account that we wanted to include intersphinx references for **multiple projects**, effectively all inventory files listed in [sphinx-inventories.txt](https://github.com/crate/crate-docs/blob/main/registry/sphinx-inventories.txt).

This has now converged into https://github.com/crate/crate-docs/issues/105, not quite reaching the goal yet, because the generated Markdown became too large to be shared on behalf of a GitHub comment 🙈.


### General Thoughts
We discovered the resources shared above per https://github.com/pyveci/pueblo/pull/73#issuecomment-2024342611, including intersphinx-untangled, only after writing this little program just out of the need that we needed it, for the same reason you outlined at https://github.com/sphinx-doc/sphinx/issues/8211, mostly frustration about needing to go the extra mile each time again and again to discover corresponding link targets from a huge documentation tree spanning multiple projects.

So, we are effectively doing corresponding orentiation flights only in retrospective, now, disovering your work on the same topic. Thank you so much!

Now, taking both sphobjinv and intersphinx-untangled into consideration, and also citing @chrisjsewell from https://github.com/orgs/sphinx-doc/discussions/12152:

> I feel it would be nicer if there was a CLI that could just be pointed at the `conf.py` and output all mappings (possibly with some "filtering" options).

Is the actual problem in (shippable) tooling here, that both sphobjinv and intersphinx-untangled work on a **per-project level**, but both @chrisjsewell and we are looking for a **multi-project** intersphinx summary output of some sorts?

With kind regards,
Andreas.

[^1]: But [also Grafana](https://community.hiveeyes.org/search?q=markdown).

**Comment by bskinn** [comment]
`sphobjinv` author here, thanks for pinging!

> We usually reach out to Markdown generation these days, because the output can be used both as a text-only variant, and for upgrading to HTML by sending it through a corresponding Markdown renderer.

Do you mean that you would like something like the following, which would generate a Markdown-formatted report of the objects in the inventory:

```bash
$ sphobjinv convert markdown objects.inv objects.md
```

If so, that should be feasible, I'd be happy to take it as a feature request.

> Is the actual problem in (shippable) tooling here, that both sphobjinv and intersphinx-untangled work on a per-project level

For `sphobjinv`, yes, I think that's right --- though, a more precise way to say it is that it works on a "per-`objects.inv` level." You point it at the generated inventory file from one specific documentation set.

It would be straightforward to write a wrapper that parses `intersphinx_mapping` out of `conf.py` and uses `sphobjinv` to create a consolidated references list. And, I can see where Markdown output from `sphobjinv` would be helpful to implement that wrapper.

I don't consider it within `sphobjinv`'s purview to actually _be_ that consolidating wrapper, though.

**Comment by amotl** [comment]
Dear @bskinn,

thanks a stack for your swift reply.

### Markdown Support
We appreciate your understanding about Markdown output, and look forward for corresponding support in sphobjinv. If the code in this PR, and the blueprint at [cratedb-sphinx-inventory-nodocs.md](https://github.com/crate/crate-docs/files/14461050/cratedb-sphinx-inventory-nodocs.md) is helpful for that, please take it consideration but also recognize it is just a minimal variant what could be done. For example, at the cost of increased file size, output could optionally use tables instead of just wrapping the main output verbatim into `text` blocks. When looking at MyST Markdown, other output variants might also become viable in future iterations.

### Multi-Project Support
> It would be straightforward to write a wrapper [to handle multi-project] processing. [...] [However,] I don't consider it within `sphobjinv`'s purview to actually _be_ that consolidating wrapper, though. 

We will be happy to explore this on behalf of `pueblo.sphinx` (this PR), by pulling in `sphobjinv`. Excellent! Because we have the need for standalone usage (i.e. without access to `conf.py`), we consider this wrapper to receive the following features aka. **variants** to seed a list of projects:

- Parse `intersphinx_mapping` out of `conf.py`, like suggested by @chrisjsewell.
- Use a list of paths or URLs to multiple `objects.inv` files, like [sphinx-inventories.txt](https://github.com/crate/crate-docs/blob/main/registry/sphinx-inventories.txt), either by providing a file, or on stdin/cmdline. This reflects the use case we have, based on the code in [tasks.py](https://github.com/crate/crate-docs/blob/main/tasks.py).
- Autodiscovery-like features on top of both variants: For example, a `conf.py` can be local or on a remote URL, possibly within a `doc` or `docs` folder within a Git project pointed at. Similarly, an `objects.inv` file can be located within a `{doc,docs}/_build/` folder within a typical Git project, or within a `/en/latest` URL path when hosted on RTD, for example. That would be just a bunch of convenience heuristics on top for people who want them.

wdyt?

With kind regards,
Andreas.

**Comment by bskinn** [comment]
@amotl:

> We appreciate your understanding about Markdown output, and look forward for corresponding support in sphobjinv.

Actually, now that I think about it further, I'm less certain whether direct Markdown output support in `sphobjinv` makes sense. My main purpose for the project is utilitarian output, for others to use as fits their needs, and not trying to customize the output formatting of `sphobjinv` itself to various users' use-cases.

So, to make sure you're aware: `sphobjinv` has an API as well as a CLI. I need to improve my documentation quite a bit to make that clearer... but, for example, you can obtain object representations of inventories via the following:

```python
>>> import sphobjinv as soi
>>> inv_local = soi.Inventory('/path/to/local/objects.inv')
>>> inv_remote = soi.Inventory(url='https://example.com/doc/latest/objects.inv')
```

As a specific example:

```python
>>> import sphobjinv as soi
>>> ( inv := soi.Inventory(url="https://sphobjinv.readthedocs.io/en/latest/objects.inv") )
Inventory(project='sphobjinv', version='2.3', source_type=<SourceTypes.URL: 'url'>)
>>> ( obj := inv.objects[0] )
DataObjStr(name='sphobjinv.cli.convert', domain='py', role='module', priority='0', uri='cli/implementation/convert.html#module-$', dispname='-')
>>> print(f"\n## {obj.name}\n\n{obj.domain}:{obj.role} ({obj.priority})\nURI Within Docset: {obj.uri_expanded}\nDefault
display name: {obj.dispname_expanded}")

## sphobjinv.cli.convert

py:module (0)
URI Within Docset: cli/implementation/convert.html#module-sphobjinv.cli.convert
Default display name: sphobjinv.cli.convert
```

So, I think `sphobjinv` already gives you everything you need to programmatically craft the Markdown you want---and, without having to worry about the `sphobjinv` release schedule.

**Comment by bskinn** [comment]
> we consider this wrapper to receive the following features aka. variants to seed a list of projects:

All of those make sense! And, it seems to me there's already interest out there in multiple of those possible modes of multi-docset cross-reference compilation. Seems like a great thing to put energy into, to me.

**Comment by amotl** [comment]
Thanks a stack for your guidance.

> So, I think `sphobjinv` already gives you everything you need to programmatically craft the Markdown you want.

After actually learning about `sphobjinv`, we already figured that would be the right approach. We will go down that path on behalf of `pueblo.sphinx`, exploring both areas of Markdown/HTML output, and the multi-project processing details outlined above. We will keep you posted and appreciate any feedback on relevant outcomes. Thank you so much!

**Comment by bskinn** [comment]
👍Good luck! Please ping me any time with questions.

**Comment by amotl** [comment]
### Filtering / DWIM

Regarding [DWIM](https://en.wikipedia.org/wiki/DWIM), as you can see in [tasks.py](https://github.com/crate/crate-docs/blob/main/tasks.py), we already need filtering capacities (`omit_documents`, `labels_only`). In this spirit, let me also reference that item of yours, mostly because it also mentions the "webapp" idea.

- https://github.com/bskinn/sphobjinv/issues/274


### Other Intersphinx Community Operations

In order to further increase community support and leverage, fragments of your nice operations could also be absorbed into code instead of hosting it on behalf of a text file in a gist, if you like that idea. My thinking is that if you already have a tool in hand that takes care about those topics in a generalized way, it would feel like an artifical boundary why it would only work on _local_ projects.

- https://github.com/bskinn/intersphinx-gist
- https://gist.github.com/bskinn/0e164963428d4b51017cebdb6cda5209

In the same spirit like @webknjaz curated a list of popular Python projects on behalf of intersphinx-untangled in YAML format, and you did on behalf of the intersphinx_mappings.txt Gist, those lists could also be written down or wrapped through Python, in order to provide easy command-line access, right?

So, instead of a possible reference research scenario like that:
```
wget https://matplotlib.org/stable/objects.inv
sphobjinv suggest objects.inv draw
```

What about such a command, effectively wrapping sphobjinv and the intersphinx_mappings gist?
```
anansi suggest matplotlib draw
```

**Comment by bskinn** [comment]
> So, instead of a possible reference research scenario like that:
> 
> ```
> wget https://matplotlib.org/stable/objects.inv
> sphobjinv suggest objects.inv draw
> ```

If I'm understanding you correctly---the `sphobjinv` CLI is already set up to pull from remote locations using the `-u` flag, and the CLI also auto-searches the provided URL for likely locations of the `objects.inv`, so in most cases a user can paste any link from the remote documentation set. E.g.,:

```cmd
>sphobjinv suggest -u https://matplotlib.org/stable/users/explain/quick_start.html#parts-of-a-figure draw

Attempting https://matplotlib.org/stable/users/explain/quick_start.html#parts-of-a-figure ...
  ... no recognized inventory.
Attempting "https://matplotlib.org/stable/users/explain/quick_start.html/objects.inv" ...
  ... HTTP error: 404 Not Found.
Attempting "https://matplotlib.org/stable/users/explain/objects.inv" ...
  ... HTTP error: 404 Not Found.
Attempting "https://matplotlib.org/stable/users/objects.inv" ...
  ... HTTP error: 404 Not Found.
Attempting "https://matplotlib.org/stable/objects.inv" ...
  ... inventory found.

------------------------------------------------------------------------

The intersphinx_mapping for this docset is LIKELY:

  (https://matplotlib.org/stable/, None)

------------------------------------------------------------------------

Project: Matplotlib
Version: 3.8.3

10431 objects in inventory.

------------------------------------------------------------------------

1 result found at/above current threshold of 75.

:std:label:`draw_idle`
```

So, if `anansi` is built to do the lookup from `intersphinx_mapping`, and thus turn `anansi suggest matplotlib draw` into an internally delegated call to `sphobjinv suggest -u https://matplotlib.org/stable/objects.inv draw`... it should work pretty cleanly, as far as I can tell.

**Comment by amotl** [comment]
> thus turn `anansi suggest` into an internally delegated call to `sphobjinv suggest ...`

Yeah exactly like this. Thanks for telling me about the `-u` option!

**Comment by bskinn** [comment]
> Ah I see, it already has the auto-discovery on board.

Only if you provide it a link from within the docset where it lives on the web.

`sphobjinv` doesn't know how to introspect `conf.py:intersphinx_mapping` to go from project name to docset URL

**Comment by amotl** [comment]
Hi again,

- We converged the wish list items into the [Linksmith RFC](https://linksmith.readthedocs.io/en/latest/rfc.html). Please let us know if you think we missed an important item you always dreamed of.
- [linksmith 0.0.1](https://github.com/tech-writing/linksmith/releases/tag/v0.0.1) has been released, and [Linksmith Usage](https://linksmith.readthedocs.io/en/latest/usage.html) has minimal usage docs.
- We are closing this PR, because corresponding concerns will now be handled within `linksmith`.
- Please create issues for any other wishes in this regard, both on ingress flexibility, and output formatting. Thanks! 🍀 

Cheers,
Andreas.

**Pull request closed without merging**
